### ISSUE TITLE
Can't import pyuaf (No module named _opcuaidentifiers)

### ISSUE THREAD

**Issue by jpfr** [uaf/uaf#23]
See below for details.
Best, Julius
```
Python 2.7.6 (default, Nov 10 2013, 19:24:18) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyuaf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Home\Tools\uaf\lib\pyuaf\__init__.py", line 2, in <module>
    from pyuaf import util, client
  File "C:\Home\Tools\uaf\lib\pyuaf\util\__init__.py", line 279, in <module>
    import opcuaidentifiers
  File "C:\Home\Tools\uaf\lib\pyuaf\util\opcuaidentifiers.py", line 28, in <module>
    _opcuaidentifiers = swig_import_helper()
  File "C:\Home\Tools\uaf\lib\pyuaf\util\opcuaidentifiers.py", line 20, in swig_import_helper
    import _opcuaidentifiers
ImportError: No module named _opcuaidentifiers
```

**Comment by WimPessemier** [comment]
It took a while, but the dlls are now copied automatically by default. 
Use the -DCOPY_SDK_LIBS=OFF flag to avoid this.
